### ISSUE TITLE
Unity WebGL doesn't work because of CORS policy

### ISSUE THREAD

**Issue by mshamrock** [GetScatter/scatter-sharp#13]
We're using Unity 2018.4.2 and latest Scatter Sharp lib version.
Local functions like Scatter.Connect() and Scatter.GetIdentity() work fine.
Under WebGL are not working EosBase.CreateTransaction() and EosBase.GetAccount() - functions related to the nodes.
I see this error message in the console:

Access to XMLHttpRequest at 'https://jungle2.cryptolions.io/v1/chain/get_block' from origin 'https://0x.games' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

UnityLoader.js:4 {"raw_error":"{\"ClassName\":\"EosSharp.Core.Exceptions.ApiException\",\"Message\":null,\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"  at EosSharp.Unity3D.HttpHandler.BuildApiError (System.String content, System.Int32 statusCode) [0x00000] in <00000000000000000000000000000000>:0 \\n  at EosSharp.Unity3D.HttpHandler.CheckUnityWebRequestErrors (UnityEngine.Networking.UnityWebRequest uwr) [0x00000] in <00000000000000000000000000000000>:0 \\n  at EosSharp.Unity3D.HttpHandler+<PostJsonAsync>d__6`1[TResponseData].MoveNext () [0x00000] in <00000000000000000000000000000000>:0 \\n  at

**Comment by mmcs85** [comment]
That is a normal error for when a EOS node does not allow cross origin requests. I would suggest you talk with crypto lions if is there a alternative of you.
Or you could spin a local testnet with CORS disabled and connect to that.

**Comment by mshamrock** [comment]
It can not be the normal issue because:
1) we notice the same problem on your node
2) this problem was not present when we used Scatter's js api

**Comment by mshamrock** [comment]
here is the log from your node:

Access to XMLHttpRequest at 'https://nodes.get-scatter.com/v1/chain/get_block' from origin 'https://0x.games/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by mmcs85** [comment]
ok I will look into it in more detail

**Comment by BestStream** [comment]
@mmcs85 Some context: We use Scatter in two games 0xWarriors and 0xRacers. Earlier we used js api. But it stopped working on Scatter 11 (on Scatter 10 still works fine). We decided to switch to Scatter sharp api, because you wrote that it works on WebGL. But it is not. As a result both our games don't work now. Please help us solve this problem

**Comment by mmcs85** [comment]
@BestStream I'm happy to help as mutch as I can.

But I want to clear right now that I'm not responsible for your decisions. This is open source software and with the use of any lib there is risk and one should give it a try before rewriting software.

**Comment by mmcs85** [comment]
So I have identified the issue. Some nodeos nodes dont return on the CORS preflight stage the header access-control-allow-headers=content-type.
 
Its required to allow json requests to nodeos nodes.

This worked before and might happen on a a nodeos version just dont know wich one.

Nodes should be configured with this:
access-control-allow-origin = *
access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept

try this one for jungle: https://api.jungle.alohaeos.com

**Comment by BestStream** [comment]
@mmcs85 Ok, we’ll check https://api.jungle.alohaeos.com for Jungle environment. But I still don’t understand the following
1) Why was there no problem on Scatter JS API, and it appeared after switching to Scatter Sharp API?
2) What node to use in the release environment? Will you fix your node nodes.get-scatter.com ?

**Comment by mmcs85** [comment]
The issue is related with eosjs and not scatter.
- eosjs sends requests with Content-Type: text/plain;charset=UTF-8
- eos-sharp sends with Content-Type: application/json.

The correct way of doing ajax requests in json is the way eos-sharp does. And as I stated it worked before.
But somehow Chrome browser started sending on CORS situations where Content-type: application/json the above headers and then some nodeos apis did not responde on the access-control-allow-headers.

There is really two ways to go: change the content-type of eos-sharp.
Change the nodeos configs to support this situations.

On mainnet you can use this: https://api.main.alohaeos.com
I'm talking with @nsjames on the best solution and to look into the node

**Comment by BestStream** [comment]
@mmcs85  I have checked and https://api.jungle.alohaeos.com works fine for Jungle! Thanks!

**Comment by BestStream** [comment]
@mmcs85  https://api.main.alohaeos.com - it works too. Thanks for help! The problem is resolved
